export enum StaffRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  AGENT = 'AGENT',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  PENDING_DEPOSIT = 'PENDING_DEPOSIT',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum ConversationStatus {
  OPEN = 'OPEN',
  WAITING = 'WAITING',
  RESOLVED = 'RESOLVED',
  SNOOZED = 'SNOOZED',
}

export enum ConversationChannel {
  WHATSAPP = 'WHATSAPP',
  WEB = 'WEB',
}

export enum MessageDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
}

export enum MessageContentType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  DOCUMENT = 'DOCUMENT',
  AUDIO = 'AUDIO',
}

export enum ReminderStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum TemplateCategory {
  REMINDER = 'REMINDER',
  CONFIRMATION = 'CONFIRMATION',
  FOLLOW_UP = 'FOLLOW_UP',
  CONSULT_FOLLOW_UP = 'CONSULT_FOLLOW_UP',
  AFTERCARE = 'AFTERCARE',
  TREATMENT_CHECK_IN = 'TREATMENT_CHECK_IN',
  DEPOSIT_REQUIRED = 'DEPOSIT_REQUIRED',
  CANCELLATION = 'CANCELLATION',
  RESCHEDULE_LINK = 'RESCHEDULE_LINK',
  CANCEL_LINK = 'CANCEL_LINK',
  CUSTOM = 'CUSTOM',
}

export enum ServiceKind {
  CONSULT = 'CONSULT',
  TREATMENT = 'TREATMENT',
  OTHER = 'OTHER',
}

export enum VerticalPack {
  AESTHETIC = 'aesthetic',
  SALON = 'salon',
  TUTORING = 'tutoring',
  GENERAL = 'general',
  DEALERSHIP = 'dealership',
}

export enum KanbanStatus {
  CHECKED_IN = 'CHECKED_IN',
  DIAGNOSING = 'DIAGNOSING',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  IN_PROGRESS = 'IN_PROGRESS',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
}
